# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b433adcbc7583ef412fe3a1c465ca0bf53dee8c01121c39c630299dd6959b1117824600fb6dc7cc2e317399b62f1ac7ed2a11146384e5825078506144121f8fd
  telegram:
    access_token: <%= ENV['TELEGRAM_ACCESS_TOKEN'] %>

test:
  secret_key_base: cef0b517e9ace5c2c5cf9911720ee54fef023e53b6009226588d92820be89b0cce474c210da5b68a87ccb7bc6667868cb6f75be8b7a76a16b9d7e58802240a89
  telegram:
    access_token: 'atokenwithnosense'

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
